name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        description: 'デバッグモードを有効にする'
        required: false
        default: false
        type: boolean
      environment:
        description: 'デプロイ環境'
        required: false
        default: 'production'
        type: choice
        options:
        - production
        - staging

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Debug Information
        env:
          VITE_GA_MEASUREMENT_ID: ${{ secrets.VITE_GA_MEASUREMENT_ID }}
          VITE_GOOGLE_SEARCH_CONSOLE_CODE: ${{ secrets.VITE_GOOGLE_SEARCH_CONSOLE_CODE }}
        run: |
          echo "=== デバッグ情報 ==="
          echo "デプロイ環境: ${{ inputs.environment }}"
          echo "ブランチ: ${{ github.ref_name }}"
          echo "コミット: ${{ github.sha }}"
          echo "実行者: ${{ github.actor }}"
          echo "環境変数確認:"
          echo "VITE_GA_MEASUREMENT_ID: ${VITE_GA_MEASUREMENT_ID:+設定済み}"
          echo "VITE_GOOGLE_SEARCH_CONSOLE_CODE: ${VITE_GOOGLE_SEARCH_CONSOLE_CODE:+設定済み}"
      - name: Build
        env:
          VITE_GA_MEASUREMENT_ID: ${{ secrets.VITE_GA_MEASUREMENT_ID }}
          VITE_GOOGLE_SEARCH_CONSOLE_CODE: ${{ secrets.VITE_GOOGLE_SEARCH_CONSOLE_CODE }}
        run: npm run build

      - name: Verify build output
        run: |
          echo "=== ビルド結果確認 ==="
          echo "dist ディレクトリの内容:"
          ls -la dist/
          echo ""
          echo "main.js の確認:"
          find dist -name "*.js" -exec echo "ファイル: {}" \; -exec head -5 {} \;
          echo ""
          echo "環境変数の値確認:"
          echo "VITE_GA_MEASUREMENT_ID: $VITE_GA_MEASUREMENT_ID"
          echo "VITE_GOOGLE_SEARCH_CONSOLE_CODE: $VITE_GOOGLE_SEARCH_CONSOLE_CODE"
        env:
          VITE_GA_MEASUREMENT_ID: ${{ secrets.VITE_GA_MEASUREMENT_ID }}
          VITE_GOOGLE_SEARCH_CONSOLE_CODE: ${{ secrets.VITE_GOOGLE_SEARCH_CONSOLE_CODE }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 