name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          echo "VITE_GA_MEASUREMENT_ID=${{ secrets.VITE_GA_MEASUREMENT_ID }}" > .env
          if [ -n "${{ secrets.GOOGLE_SEARCH_CONSOLE_CODE }}" ]; then
            echo "VITE_GOOGLE_SEARCH_CONSOLE_META=<meta name=\"google-site-verification\" content=\"${{ secrets.GOOGLE_SEARCH_CONSOLE_CODE }}\" />" >> .env
          else
            echo "VITE_GOOGLE_SEARCH_CONSOLE_META=" >> .env
          fi
          cat .env

      - name: Build
        run: npm run build

      - name: Replace environment variables in HTML
        run: |
          if [ -n "${{ secrets.GOOGLE_SEARCH_CONSOLE_CODE }}" ]; then
            SEARCH_CONSOLE_META="    <meta name=\"google-site-verification\" content=\"${{ secrets.GOOGLE_SEARCH_CONSOLE_CODE }}\" />"
          else
            SEARCH_CONSOLE_META=""
          fi
          
          # HTMLファイルの内容を確認
          echo "Before replacement:"
          grep -n "VITE_GOOGLE_SEARCH_CONSOLE_META" dist/index.html || true
          
          # より確実な置換（空白文字やパターンの違いに対応）
          sed -i '/VITE_GOOGLE_SEARCH_CONSOLE_META/c\'"${SEARCH_CONSOLE_META}" dist/index.html
          
          # 置換結果を確認
          echo "After replacement:"
          grep -A2 -B2 "google-site-verification" dist/index.html || echo "No meta tag found"
          echo "Checking if placeholder still exists:"
          grep "VITE_GOOGLE_SEARCH_CONSOLE_META" dist/index.html || echo "Placeholder successfully removed"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 